baseurl = "https://geekbuilt.github.io/cissp" # Controls base URL sitewide
languageCode = "en-US" # Controls site language
title = "GeekBuilt ⭐ "
paginate = 6 # Number of posts to show before paginating
copyright = "Powered by  <a target=\"_blank\" rel=\"external noopener license\" href=\"https://discourse.gohugo.io\">Hugo</a>. " # Optional, remove to suppress copyright notices
publishDir = "./docs"
# Controls default theme and theme components
theme = [
  "fractal-forest", # OBSD
  "after-dark" # AGPL-3.0-or-later
]
[params.hackcss]
  disabled = false
  mode = "hack"

disableLiveReload = false # Optional, set true to disable live reload
enableRobotsTXT = true # Suggested, enable robots.txt file

pygmentsCodefences = true # Suggested, highlight fenced code blocks
pygmentsUseClasses = true # Required for custom syntax highlighting

sectionPagesMenu = "main" # Enable menu system for lazy bloggers
footnoteReturnLinkContents = "↩" # Provides a nicer footnote return link

[params]
  description = "CISSP Study Materials" # Suggested, controls default description meta
  author = " GeekBuilt ⭐️" # Optional, controls author name display on posts
  github = "https://github.com/geekbuilt"
  hide_author = false # Optional, set true to hide author name on posts
  disable_csp = false # Optional, set true to disable content security policy
  images = [
    "https://source.unsplash.com/collection/983219/1080x720"
  ] # Suggested, controls default Open Graph images
  related_content_limit = 5

[params.seo]
  referrer = "same-origin"

[params.layout.menu.main]
  hidden = false # Optional, set false or remove to show section menu

[params.layout.footer]
  hidden = false # Optional, set true to hide footer

[params.modules.fractal_forest]
  enabled = true # Optional, set false to disable module
  decoders = ["bpgdec8a"] # Optional, 8-bit javascript decoder with animation


[params.layout.home]
  hide_blog = true
 [markup]
  defaultMarkdownHandler = "goldmark"
  [markup.tableOfContents]
    endLevel = 4
    startLevel = 1
   [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true

[[menu.main]]
 name = "home"
  weight = 3
  identifier = "home"
   url = "/"
   
[[menu.main]]
  name = "posts"
  weight = 4
  identifier = "post"
  url = "/post/"

[[menu.main]]
  name = "search"
  weight = 5
  identifier = "search"
  url = "/search/"

[params.layout.post.featured]
  limit = 2
  items = [
    "cissp-study",
    "guides-and-notes"
  ]

[outputs]
  home = ["HTML", "RSS", "JSON"]

[sitemap]
  changefreq = "monthly"
  filename = "sitemap.xml"
  priority = 0.5

[taxonomies]
  category = "categories"
  tag = "tags"

[[params.layout.home.section]]
  type = "post" # Required, name of section to show on homepage
  limit = 2 # Optional, set number of items to show from section
  weight = 2 # Optional, choose layout order for section
  thumbs = ["fill", "400x400"] 

  keywords = [
  "best practices",
  "benchmarks",
  "tools",
  "windows server",
  "guides",
  "windows 2019",
  "IT security",
  "web hosting",
  "cissp"
]
googleAnalytics = "UA-128579459-3"
[params.seo.webmaster_verifications]
  google = "" # Optional, see https://search.google.com/search-console
  bing = "" # Optional, see https://www.bing.com/toolbox/webmaster/
  yandex = "51825b18e88d5811" # Optional, see https://webmaster.yandex.com/
  alexa = "" # Optional, claiming retired (see note below)

 	

 	

